[package]
name = "embed-deno"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_runtime = "0.18.1"
deno_core = "0.91.1"
tokio = "1.7.1"
gag = "1.0.0"